### ISSUE TITLE
Running opencl_ruby_ffi in a forked process

### ISSUE THREAD

**Issue by mtbikerjc** [Nanosim-LIG/opencl-ruby#10]
Is there a correct way of running opencl_ruby_ffi in a forked process?

My ruby code oftentimes forks a ruby process that executes opencl_ruby code...  the previous version of opencl_ruby_ffi allowed me to do this as long as I don't initialize opencl_ruby_ffi in a parent process, and then execute code in a child process.  To make this work, I would only initialize and run opencl_ruby_ffi within child processes as necessary.

The recent version of opencl_ruby_ffi fails to execute code within a forked process, which makes me believe that it's being initialized the minute ruby loads the library.

The warnings, errors are:
> Warning: could not find extension function clGetKernelSubGroupInfoKHR!
> /var/lib/gems/2.3.0/gems/opencl_ruby_ffi-1.3.2/lib/opencl_ruby_ffi/opencl_ruby_ffi_base.rb:236:in `error_check': -33 (OpenCL::Error::INVALID_DEVICE)
> 

Is it possible to run opencl_ruby_ffi in a forked process?  And if so, what would be the correct way?  Below is a modified version of your sample code that fails when running in a forked process (this code works if the 'require' line is inserted inside the fork block):

```
require 'opencl_ruby_ffi'

pid = fork {

source = <<EOF
__kernel void addition( float2 alpha, __global const float *x, __global float *y) {
  size_t ig = get_global_id(0);
  y[ig] = (alpha.s0 + alpha.s1 + x[ig])*0.3333333333333333333f;
}
EOF

        platform = OpenCL::platforms.first
        device = platform.devices.first
        context = OpenCL::create_context(device)

        queue = context.create_command_queue(device,
                                :properties => OpenCL::CommandQueue::PROFILING_ENABLE)
        prog = context.create_program_with_source( source )
        prog.build
        a_in = NArray.sfloat(65536).random(1.0)
        a_out = NArray.sfloat(65536)
        f = OpenCL::Float2::new(3.0,2.0)
        b_in = context.create_buffer(a_in.size * a_in.element_size,
                                :flags => OpenCL::Mem::COPY_HOST_PTR,
                                :host_ptr => a_in)
        b_out = context.create_buffer(a_out.size * a_out.element_size)
        event = prog.addition(queue, [65536], f, b_in, b_out, :local_work_size => [128])
        # #Or if you want to be more OpenCL like:
        # k = prog.create_kernel("addition")
        # k.set_arg(0, f)
        # k.set_arg(1, b_in)
        # k.set_arg(2, b_out)
        # event = queue.enqueue_ndrange_kernel(k, [65536],:local_work_size => [128])
        queue.enqueue_read_buffer(b_out, a_out, :event_wait_list => [event])
        queue.finish
        diff = (a_in - a_out*3.0)
        65536.times { |i|
          raise "Computation error #{i} : #{diff[i]+f.s0+f.s1}" if (diff[i]+f.s0+f.s1).abs > 0.00001
        }
        puts "Success!"
}
Process.waitall
puts "Done executing."

```

**Comment by mtbikerjc** [comment]
For now I'm only initializing opencl_ruby_ffi from within the detached processes, to allow multiple concurrent OpenCL executions.  It's a dirty solution, but seems to work (see code snippet below).

`
#require 'opencl_ruby_ffi'

pid = fork {
        require 'opencl_ruby_ffi'

...(OpenCL_ruby code goes here)...

}
Process.waitall

puts "Done executing."
 `

**Comment by Kerilk** [comment]
I am unable to reproduce your error using my machine and the three implementations I have available. I copy pasted your first post's code in a file named fork_test.rb and when I run it I always get:
```
$ ruby fork_test.rb 
Success!
Done executing.
 ```

Ubuntu 16.04
ruby 2.3.0p0 (2015-12-25)
ocl-icd 2.2.8-1
NVIDIA GPU 361.42
opencl-1.2-5.2.0.10002
OpenCL 2.0 AMD-APP (1912.5)

Maybe the implementation you are using is bugged and doesn't like to be forked (internal state problems). Or maybe you libOpenCL.so if it is not ocl-icd (or an old version).

If it was the case you could use out of order queues with events and enqueue all your kernels at once (or use multiple queues / combination of those).

Sorry I am not of much help on this one.

**Comment by mtbikerjc** [comment]
Thanks for looking into this, it might very well be a problem at my end, possibly from Nvidia's OpenCL icd.

I'm running Ubuntu 16.04
ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]
Nvidia GTX 1080, GTX 980
Nvidia driver libnvidia-opencl.so.367.27
Nvidia's OpenCL icd (This may be the cause of the problem, I'll try installing ocl-icd)

**Comment by mtbikerjc** [comment]
Unfortunately, installing ocl-icd-libopencl1 doesn't fix the issue.  I also followed these steps to try to force Ubuntu to use ocl-id: https://wiki.archlinux.org/index.php/GPGPU (mainly, creating a file /etc/ld.so.conf.d/00-usrlib.conf that points to the ocl-icd location).

I suspect the problem may be with the newer driver version; unfortunately, I can't downgrade to NVIDIA GPU driver 361.42 since the earlier drivers don't support GTX 1080.

**Comment by mtbikerjc** [comment]
I just came across an Nvidia thread saying that an OpenCL or Cuda device can't be used by a forked process after it's been initialized by the parent.  It may work here and there, but the behaviour is undefined:
[https://devtalk.nvidia.com/default/topic/538669/gpu-accelerated-libraries/problem-with-gtx-titan-opencl-linux-library-and-or-driver/](url)
Hope this helps someone!
Brice, please set this post as resolved.

**Comment by Kerilk** [comment]
Thanks for investigating.
