### ISSUE TITLE
support for Numo::NArray

### ISSUE THREAD

**Issue by kojix2** [Nanosim-LIG/opencl-ruby#11]
Hi
Thank you for your great work. opencl-ruby is the best way to use the GPU in Ruby as far as I know . I'd appreciate it if you could support new NArray class library Ruby/Numo::NArray . 
Thank you.

**Comment by Kerilk** [comment]
Hello,

I asked a NArray developers their [view](https://github.com/ruby-numo/narray/issues/27) about the subject.

Regards

**Comment by kojix2** [comment]
Nearly five years have passed.
Now, @mrkn and Ruby developers are trying to support memoryview, and there is an initiative to make numo-narray available for it. I will close this issue.

https://docs.ruby-lang.org/en/master/doc/memory_view_md.html
https://tech.speee.jp/entry/2020/12/24/093131 (Japanese article by mrkn)

https://github.com/ruby-numo/numo-narray/issues/173

keep your great work!
