### ISSUE TITLE
slow to load

### ISSUE THREAD

**Issue by logicminds** [Nanosim-LIG/opencl-ruby#12]
the opencl-ruby library takes  few seconds to load.  If I am just interested in getting the device info do I need all the other libraries that are loaded in lib/opencl_ruby_ffi.rb?

If I try to just load opencl_ruby_ffi/Device.rb  I get 
```
NameError: uninitialized constant OpenCLRefinements
from /opt/crossbelt/embedded/lib/ruby/gems/2.5.0/gems/opencl_ruby_ffi-1.3.4/lib/opencl_ruby_ffi/Device.rb:1:in `<top (required)>'

```

Is there any other way to speed up the discovery of opencl devices?

**Comment by logicminds** [comment]
I am probably answering my own question but these seem to be the only required libraries to list the devices.  Loading just these libraries didn't seem to save that much time either.  

The bulk of the load time  (1000 ms) seems to rest solely on "opencl_ruby_ffi/ext.rb".  

```
require "opencl_ruby_ffi/opencl_types.rb"
require "opencl_ruby_ffi/opencl_ruby_ffi_base_gen.rb"
require "opencl_ruby_ffi/opencl_arithmetic_gen.rb"
require "opencl_ruby_ffi/opencl_ruby_ffi_base.rb"
require "opencl_ruby_ffi/Context.rb"
require "opencl_ruby_ffi/Platform.rb"
require "opencl_ruby_ffi/Device.rb"
require "opencl_ruby_ffi/CommandQueue.rb"
require "opencl_ruby_ffi/Mem.rb"
require "opencl_ruby_ffi/ext.rb"
```

Is there any way to improve the load time of the ext.rb library?

**Comment by Kerilk** [comment]
I'll have more time next week, but basically the problems is two fold:
 * The first time an OpenCL platform is used (first function call to this platform) it is initialized,
 * When ext.rb is loaded the OpenCL platforms are queried to find out what extensions they support thus initializing them.
Your problem is most probably that you have a platform that is slow to initialize.  Removing ext.rb would delay the problem until you query the devices . You should be able to confirm that by using the command line tool clinfo and check if you experience long loading times. On my platform (with several OpenCL platforms installed) both are instantaneous.

**Comment by logicminds** [comment]
Yea CLinfo is slow on AMD RX 580s.  I ended up caching the cl devices so I can just prevent usage of OpenCL.  This is for a CLI app so it gets initialized upon every execution.


```ruby
     # @returns [Array] - an array of openstruct objects
      def self.opencl_devices_from_platform
        require "ostruct"
        require 'opencl_ruby_ffi'
        # opencl takes a second to load so we cache these in a serialized object later in the process
        OpenCL::platforms.map(&:devices).flatten.map do |d|
          type = d.platform.name.include?('AMD') ? "AMD" : "Nvidia"
          board_name = type == 'AMD' ? d.board_name_amd : ""
          OpenStruct.new({
                             name: d.name,
                             type: type,
                             board_name: board_name,
                             max_compute_units: d.max_compute_units
                         })

        end
      end
```

**Comment by Kerilk** [comment]
Okay. I am not sure if I can do something about it in the main library though. Do you consider the issue closed?

**Comment by logicminds** [comment]
About the only thing you can do is have the device or platform library only load required libraries.  However, in my testing this didn't save much time and probably isn't worth the effort in less you are already refactoring the code.

**Comment by Kerilk** [comment]
That would mean adding hooks and using methods missing extensively. I'll think about it. Thanks for the report.
