### ISSUE TITLE
undefined method `error_check' for OpenCL::Event:Class (NoMethodError)

### ISSUE THREAD

**Issue by dpblnt** [Nanosim-LIG/opencl-ruby#16]
/usr/local/lib64/ruby/gems/3.1.0/gems/opencl_ruby_ffi-1.3.11/lib/opencl_ruby_ffi/opencl_ruby_ffi_base_gen.rb:1573>, @autorelease=true>
/usr/local/lib64/ruby/gems/3.1.0/gems/opencl_ruby_ffi-1.3.11/lib/opencl_ruby_ffi/opencl_ruby_ffi_base_gen.rb:1580:in `release': undefined method `error_check' for OpenCL::Event:Class (NoMethodError)

      error_check( error )
      ^^^^^^^^^^^
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/autopointer.rb:175:in `call'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/autopointer.rb:175:in `release'
        from /usr/local/lib64/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/autopointer.rb:150:in `call'

**Comment by Kerilk** [comment]
Thanks for reporting this one. I fixed it and released v1.3.13.
