### ISSUE TITLE
`create_command_queue': uninitialized constant Thread::Queue::PROPERTIES

### ISSUE THREAD

**Issue by rahulkmr** [Nanosim-LIG/opencl-ruby#5]
Hi,

I am unable to run the sample program. This is the sample I am trying to run. 

http://stackoverflow.com/a/27064531/648964

I am on Ubuntu 14.04. I installed amd opencl sdk, opencl headers and did "sudo ldconfig". I am running the proprietary catalyst driver. I am not sure if opencl installed correctly. I was using ruby to check which threw the error.

**Comment by rahulkmr** [comment]
opencl is setup fine. I just copy pasted a vector addition c program, compiled and ran it.

     gcc -I /opt/AMDAPPSDK-2.9-1/include -L /opt/AMDAPPSDK-2.9-1/lib/x86_64/ vecadd.c -l OpenCL

**Comment by Kerilk** [comment]
Thanks for the bug report. The issue should be corrected in the newer versions. Your OpenCL implementation is 2.0 and the bindings have been insufficiently tested with this version. Don't hesitate if you encounter further issues.
