### ISSUE TITLE
Passing A Mixed-Type Array to and from the GPU

### ISSUE THREAD

**Issue by mtbikerjc** [Nanosim-LIG/opencl-ruby#6]
I'm new to GPU programming and don't know where else to ask this question, but is it possible to pass a mixed-type array to the GPU and back without using an NArray?  NArray lets me create arrays of a single type, or of a ruby "object" (which I believe is a pointer to a ruby object), but those don't work for my purposes.  My setup is Linux, with an NVidia GTX-980 GPU.

I'm processing time-series event data in the GPU using the following struct:
`typedef struct {
  int   start_date;
  int   end_date;
  float starting_value;
  float delta;
} event;`

So, I need some array elements to be integers, and others to be floating points.

I was able to create an NArray in ruby of type "object" (a Ruby object) that stores and processes arrays with mixed type elements, and was even able to convert it to a Marshalled object and back with no problems.  I run into problems when I try passing the NArray to the GPU, or try passing such a mixed-type array back to Ruby from the GPU.  I'm sure the problem is that the ruby "object" is  a reference pointer, and the opencl-ruby "create_buffer" or the "enqueue_read_buffer" functions may be treating them as integers without dereferencing the pointers.

Is there any other way to pass a block of mixed data types from ruby to the GPU without using an NArray?  Or would it be possible to modify the opencl-ruby code to iterate through an NArray of type "object" to pass the individual integer and float values to the buffer?

Thanks!  I'd appreciate any help or insight you can give me.

Cheers,
Jorge

**Comment by mtbikerjc** [comment]
I've been reading further into this, and think the best solution may be to create a ruby extension in C that allocates memory for my time-series data, and reads the results I get from the GPU.  I noticed from the opencl-ruby code description that the `create_buffer()` function takes in any object that can be converted to a pointer via a call to `to_ptr(),` so my ruby extension will need a `to_ptr()` function to access the memory allocated in C.
    http://opencl-ruby.forge.imag.fr/index.html#method-c-create_buffer

Is this the preferred solution?

**Comment by Kerilk** [comment]
Yes this is what I have in mind. We need to have an object delivering 
the correct memory layout. But before you spend a lot of time doing a 
native extension I would to do some research to find whether some gems 
exist that do C object serialization/mapping. NArray was for simple 
types but maybe someone had your needs before in another context.

I should get back to you in a few hours.

**Comment by Kerilk** [comment]
Jorge,

I have added an example showing the usage of array of struct using FFI (which is the underlying interface to OpenCL here).
You can find this example here:
https://github.com/Nanosim-LIG/opencl-ruby/blob/master/opencl_ruby_ffi/test/structure_test.rb
I think it will be sufficient for your needs.

Tell me if you still have issues.

Regards,

Brice

**Comment by mtbikerjc** [comment]
Thanks Brice!  Your example is straight to the point, and easy to implement.  This is exactly what I needed.Best regards,JorgeOn September 14, 2015 at 4:11 AM Brice Videau <notifications@github.com> wrote:Jorge,I have added an example showing the usage of array of struct using FFI (which is the underlying interface to OpenCL here). You can find this example here: https://github.com/Nanosim-LIG/opencl-ruby/blob/master/opencl_ruby_ffi/test/structure_test.rb I think it will be sufficient for your needs.Tell me if you still have issues.Regards,Brice—Reply to this email directly or view it on GitHub.

**Comment by Kerilk** [comment]
Jorge,

In order to reduce the impact of opencl_ruby_ffi on the Underlying FFI library I had to change a bit the behaviour of the Structure layout method. you should use:

```
class EV < FFI::Struct
  layout :start_date, OpenCL::Int,
         :data, OpenCL::Int2,
         :starting_value, OpenCL::Float,
         :delta, OpenCL::Float
end
```
instead of the previous:
```
class EV < FFI::Struct
  layout :start_date, :cl_int,
         :data, OpenCL::Int2,
         :starting_value, :cl_float,
         :delta, :cl_float
end
```
Sorry for any inconvenience it might cause.

Regards,

Brice

I aliased CL and OpenCL so ou can also use CL:Int.

**Comment by mtbikerjc** [comment]
Thanks for looking out Brice!  You're amazing.
Best regards,
Jorge
