### ISSUE TITLE
How to stop warning 'Warning OpenCL 1.x loader detected!'

### ISSUE THREAD

**Issue by MatzFan** [Nanosim-LIG/opencl-ruby#7]
Just starting with your excellent library, having just successfully written my first OpenCL program in Ruby (vector addition) :smile:

One niggle: Every time I load the gem file thus, this warning goes to STDOUT. Right at the end of [here](https://github.com/Nanosim-LIG/opencl-ruby/blob/master/opencl_ruby_ffi/lib/opencl_ruby_ffi/opencl_ruby_ffi_base_gen.rb) it seems to auto detect my OpenCL 1.2 framework, which is great, but if I want to suppress the warning how do I do this? Many thanks
```
require 'opencl_ruby_ffi'
```

OS: OS X 10.9.5

**Comment by Kerilk** [comment]
Hello,
Thanks for your kind interest.
If you want to disable the warnings you can use:
```ruby
def silence_warnings(&block)
  warn_level = $VERBOSE
  $VERBOSE = nil
  result = block.call
  $VERBOSE = warn_level
  result
end

silence_warnings { require 'opencl_ruby_ffi' }
```
It is the classical way to do it in ruby.
As those warnings are generated during the library loading you can't really do it any other way.
Unfortunately as the gem supports OpenCL 2.0 this warning is necessary.

**Comment by MatzFan** [comment]
Perfect, many thanks Brice

Bruce
